# Generated by Django 5.2.7 on 2025-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('BRAIN_TUMOR', 'Brain Tumor Detection'), ('ALZHEIMER', 'Alzheimer Detection'), ('STROKE', 'Stroke Detection')], max_length=50)),
                ('input_file', models.FileField(upload_to='scans/')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
