# Generated by Django 5.2.7 on 2026-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='clinical_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
