# Generated by Django 5.2.7 on 2025-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='annotated_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
