# Generated by Django 5.2.6 on 2025-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20250927_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
